lib/twix_web/router.ex
defmodule TwixWeb.Router do
  use TwixWeb, :router

  alias TwixWeb.Plugs.SetUser

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TwixWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug(SetUser)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TwixWeb do
    pipe_through :browser

    get("/", HomeController, :index)
    resources("/auth", AuthController, only: [:new, :create])
    delete("/sign_out", AuthController, :delete)
    resources("/registration", RegistrationController, only: [:new, :create])

    resources("/chat/rooms", RoomController, only: [:new, :create])

    live "/feed", FeedLive, :index
    live "/feed/create", FeedLive.Create, :create

    live "/chat/rooms", ChatLive, :index
    live "/chat/room/:name", ChatLive.Room, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TwixWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TwixWeb.Telemetry
    end
  end
end

lib/twix_web/views/layout_view.ex
defmodule TwixWeb.LayoutView do
  use TwixWeb, :view
end

lib/twix_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/twix_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/twix_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Twix", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

    <script>
      M.AutoInit();
    </script>

  </head>
  <body>
    <header>
      <section>
        <div class="fixed-action-btn">
              <%= if @conn.request_path === Routes.feed_path(@conn, :index) do %>
                <%= link "Create Post", to:
                Routes.feed_create_path(@conn, :create), class: "btn grey darken-2" %>
              <% end %>
        </div>
        <nav role="navigation">
        <div class="nav-wrapper">
          <div class="container">
            <%= link "Twix", class: "brand-logo grey-text", to: Routes.home_path(@conn, :index) %>
            <ul class="right">
              <%= if @user_signed_in? do %>
              <li>
                <%= link "Feed", class: "grey darken-2 btn hide-on-small-only", to:
                Routes.feed_path(@conn, :index) %>
              </li>
              <li>
                <%= link "Sign Out", class: "grey darken-2 btn hide-on-small-only", to:
                Routes.auth_path(@conn, :delete), method: :delete %>
              </li>
              <% else %>
              <li>
                <%= link "Sign In", class: "btn grey darken-2 hide-on-small-only", to: Routes.auth_path(@conn, :new) %>
              </li>
              <li>
                <%= link "Sign Up", class: "btn grey darken-2 hide-on-small-only", to: Routes.registration_path(@conn, :new) %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
        </nav>
        <ul id="slide-out" class="sidenav blue-grey darken-4 white-text">
     <li>
      <a href="/" class="white-text">
      <i class="material-icons white-text">chat</i>
      Twix
      </a>
     </li>
    <%= if @user_signed_in? do %>
    <li>
      <%= link "Feed", class: "waves-effect white-text waves-white", to:
      Routes.feed_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Rooms", class: "waves-effect white-text waves-white", to:
      Routes.chat_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Create Room", class: "waves-effect white-text waves-white", to:
      Routes.room_path(@conn, :new) %>
    </li>
    <li>
      <%= link "Sign Out", class: "waves-effect white-text waves-white", to:
      Routes.auth_path(@conn, :delete), method: :delete %>
    </li>
    <% else %>
    <li>
      <%= link "Sign In", class: "waves-effect white-text waves-white", to: Routes.auth_path(@conn, :new) %>
    </li>
    <li>
      <%= link "Sign Up", class: "waves-effect white-text waves-white", to: Routes.registration_path(@conn, :new) %>
    </li>
    <% end %>
  </ul>
      </section>
      <div class="container">
        <div data-target="slide-out" class="sidenav-trigger left pointer"><i class="material-icons blue-grey-text darken-4">menu</i></div>
      </div>
    </header>
    <%= @inner_content %>
  </body>
</html>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const elems = document.querySelectorAll('.sidenav');
    const instances = M.Sidenav.init(elems);
  });
</script>